apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarydb
  template:
    metadata:
      labels:
        app: librarydb
    spec:
      containers:
        - name: librarydb
          image: debezium/postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: librarydb
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              value: test
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: librarydb
spec:
  selector:
    app: librarydb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP